---
title: Supplementary Protocols 1 – 4 
author: "Ruth Isserlin"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_notebook:
    highligh: haddock
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
  html_document:
    highligh: haddock
    keep_md: yes
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
bibliography: sup_protocol1_references.bib
csl: nature-protocols.csl
---

```{r autodoc, child='supplementary_protocols123_setup.Rmd', eval=TRUE, echo=TRUE}
``` 

```{r include=FALSE}
add_setup = FALSE
```

```{r autodoc, child='supplemental_protocol1_rnaseq.Rmd', eval=TRUE, echo=TRUE}
``` 

```{r autodoc, child='supplemental_protocol2_microarray.Rmd', eval=TRUE, echo=TRUE}
``` 

```{r autodoc, child='supplemental_protocol3_R_gse_methods.Rmd', eval=TRUE, echo=TRUE}
``` 

```{r autodoc, child='Supplemental_protocol_4_manual_phenotype_rand_with_edgeR.Rmd', eval=TRUE, echo=TRUE}
``` 

## References
